services:
  - type: web
    name: data-analysis-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 4 --threads 2 --timeout 120 app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /health