services:
  - type: web
    name: your-backend-name # You can change this name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app # Corrected: points directly to app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13