services:
  - type: web
    name: dane-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    autoDeploy: true
